import { Arvo } from "next/font/google";
import "./globals.css";
import NavLink from "@/components/NavLinks";




const arvo = Arvo({ subsets: ["latin"], weight: ['400'] });

export const metadata = {
  title: "Pokedex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${arvo.className} antialiased w-screen overflow-x-hidden relative`}>
      <NavLink />
      {children}
      </body>
    </html>
  );
}
