import { Arvo } from "next/font/google";
import "./globals.css";
import NavLink from "@/components/NavLinks";
import Image from "next/image";



const arvo = Arvo({ subsets: ["latin"], weight: ['400'] });

export const metadata = {
  title: "Pokedex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${arvo.className} antialiased w-screen h-screen overflow-x-hidden overflow-y-scroll`}>
      <NavLink />
      {children}
      </body>
    </html>
  );
}
